### ISSUE TITLE
Ordering of streams for a single event

### ISSUE THREAD

**Issue by usrbowe** [sportclimbing/ifsc-calendar#15]
Would it be possible to order streams for event based on the nearest streaming time.

Currently the order is static and based on the time it is planned to stream or already passed the stream.

We could prioritise upcoming/live streams to be on top.

Current view:
![IMG_7749](https://github.com/sportclimbing/ifsc-calendar/assets/5339061/c7022331-7f8d-4ab3-9b68-edd2b0c08b1a)

Can push this stream on top:
![IMG_7750](https://github.com/sportclimbing/ifsc-calendar/assets/5339061/6cf6ee76-ec9c-4c5e-a7d7-4a5c8d43cbc2)

**Comment by nicoSWD** [comment]
Hey @usrbowe 

I like this idea! Let me think this through and come up with a good solution for this.

By the way, thank you so much for your generous donation! 🥹 It really means a lot!

**Comment by nicoSWD** [comment]
@usrbowe done! Might make it a little prettier but it should work for now! (Looks better on desktop)

Thank you!

https://github.com/sportclimbing/web/pull/3
