### ISSUE TITLE
Will you update for 2024?

### ISSUE THREAD

**Issue by annaken** [sportclimbing/ifsc-calendar#2]

**Comment by nicoSWD** [comment]
Hey @annaken 

yes, absolutely! I'm waiting for the IFSC to post the proper schedules. I'm parsing the event pages to obtain the info, but there's nothing yet. See https://www.ifsc-climbing.org/index.php/component/ifsc/?view=event&WetId=1353 for example.

This should hopefully change soon.

**Comment by annaken** [comment]
Amazing, thank you! There are some events on https://www.ifsc-climbing.org/index.php/world-competition/calendar but they're annoying to parse as they're all split up.

**Comment by nicoSWD** [comment]
Thanks! Yeah, I'm aware. The problem with these is that they're not very detailed. I want the calendar to show proper times (not just dates) and which kind of event is being held (discipline, semis, finals, etc).

I might add some functionality later that shows the date range if nothing else is available, and then the details once they're published.

**Comment by annaken** [comment]
Gotcha. Thanks again!

**Comment by nicoSWD** [comment]
You're welcome! Thanks for your support ❤️

**Comment by annaken** [comment]
❤️

**Comment by annaken** [comment]
Perfect! Added to my calendar- thank you 😄
