### ISSUE TITLE
Expired certificate for calendar.ifsc.stream

### ISSUE THREAD

**Issue by mystygage** [sportclimbing/ifsc-calendar#24]
The TLS certificate for https://calendar.idsc.stream is expired:

![image](https://github.com/user-attachments/assets/fe1f9a6b-3b87-447e-9228-e999878da588)

**Comment by nicoSWD** [comment]
Thanks @mystygage!

I was on a trip and didn't have access. It should be working again!

**Comment by mystygage** [comment]
Thank you, works like a charm.
